Repository codeit-sprint-team6/sb01-Findex-Team6, pull requests merged in 2025-03, with the labels that each got.

#12 feat: 지수 데이터 연동 개발 및 엔티티 필드 이름 수정, 의존성 추가
  .DS_Store
  build.gradle
  src/.DS_Store
  src/main/java/com/sprint/findex_team6/controller/SyncJobsController.java
  src/main/java/com/sprint/findex_team6/dto/DashboardDto.java
  src/main/java/com/sprint/findex_team6/dto/SyncJobDto.java
  src/main/java/com/sprint/findex_team6/dto/request/IndexDataSyncRequest.java
  src/main/java/com/sprint/findex_team6/entity/ContentType.java
  src/main/java/com/sprint/findex_team6/entity/Index.java
  src/main/java/com/sprint/findex_team6/entity/IndexDataLink.java
  src/main/java/com/sprint/findex_team6/exception/SyncDataJobsServiceExceptionHandler.java
  src/main/java/com/sprint/findex_team6/exception/SyncJobErrorCode.java
  src/main/java/com/sprint/findex_team6/mapper/DashboardMapper.java
  src/main/java/com/sprint/findex_team6/mapper/IndexValMapper.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepository.java
  src/main/java/com/sprint/findex_team6/repository/IndexRepository.java
  src/main/java/com/sprint/findex_team6/service/IndexService.java
  src/main/java/com/sprint/findex_team6/service/SyncDataJobsService.java
  src/test/java/com/sprint/findex_team6/mapper/IndexDateLinkMapperTest.java
  src/test/java/com/sprint/findex_team6/service/SyncDataJobsServiceTest.java
Labels: ✨ Feature, 📃 Docs, 🐞 BugFix

#18 feat: 지수 정보 연동
  src/main/java/com/sprint/findex_team6/controller/SyncJobsController.java
  src/main/java/com/sprint/findex_team6/dto/AutoIntegrationDto.java
  src/main/java/com/sprint/findex_team6/dto/SyncJobDto.java
  src/main/java/com/sprint/findex_team6/mapper/AutoIntegrationMapper.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepository.java
  src/main/java/com/sprint/findex_team6/service/SyncJobsService.java
Labels: ✨ Feature, 🔨 Refactor

#19 feat: add 차트조회기능
  src/main/java/com/sprint/findex_team6/controller/IndexValController.java
  src/main/java/com/sprint/findex_team6/dto/dashboard/ChartDataPoint.java
  src/main/java/com/sprint/findex_team6/dto/dashboard/DashboardDto.java
  src/main/java/com/sprint/findex_team6/dto/dashboard/IndexChartDto.java
  src/main/java/com/sprint/findex_team6/entity/PeriodType.java
  src/main/java/com/sprint/findex_team6/mapper/DashboardMapper.java
  src/main/java/com/sprint/findex_team6/mapper/IndexValMapper.java
  src/main/java/com/sprint/findex_team6/repository/IndexValRepository.java
  src/main/java/com/sprint/findex_team6/service/IndexValService.java
  src/test/java/com/sprint/findex_team6/mapper/DashboardMapperTest.java
Labels: ✨ Feature

#26 feat: 지수 데이터 연동
  src/main/java/com/sprint/findex_team6/dto/SyncJobDto.java
  src/main/java/com/sprint/findex_team6/entity/Index.java
  src/main/java/com/sprint/findex_team6/entity/IndexVal.java
  src/main/java/com/sprint/findex_team6/repository/IndexValRepository.java
  src/main/java/com/sprint/findex_team6/service/SyncDataJobsService.java
Labels: ✨ Feature

#28 feat: 연동 작업 목록 커서 기반 페이징
  src/main/java/com/sprint/findex_team6/controller/SyncJobsController.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepository.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepositoryImpl.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepositoryQuerydsl.java
  src/main/java/com/sprint/findex_team6/repository/IndexValRepository.java
  src/main/java/com/sprint/findex_team6/service/SyncJobsSearchService.java
Labels: ✨ Feature

#30 fix:차트조회, 랭킹조회, 관심지수 조회 기능 수정/ feat:csv export 기능 심화구현
  src/main/java/com/sprint/findex_team6/config/QueryDSLConfig.java
  src/main/java/com/sprint/findex_team6/controller/IndexValController.java
  src/main/java/com/sprint/findex_team6/dto/DashboardDto.java
  src/main/java/com/sprint/findex_team6/dto/dashboard/ChartDataPoint.java
  src/main/java/com/sprint/findex_team6/dto/dashboard/ErrorResponse.java
  src/main/java/com/sprint/findex_team6/dto/dashboard/IndexChartDto.java
  src/main/java/com/sprint/findex_team6/dto/dashboard/IndexPerformanceDto.java
  src/main/java/com/sprint/findex_team6/dto/dashboard/IndexValCsvDto.java
  src/main/java/com/sprint/findex_team6/dto/dashboard/IndexValDto.java
  src/main/java/com/sprint/findex_team6/dto/dashboard/RankedIndexPerformanceDto.java
  src/main/java/com/sprint/findex_team6/entity/AutoIntegration.java
  src/main/java/com/sprint/findex_team6/entity/Dashboard.java
  src/main/java/com/sprint/findex_team6/entity/IndexDataLink.java
  src/main/java/com/sprint/findex_team6/entity/IndexVal.java
  src/main/java/com/sprint/findex_team6/error/CustomException.java
  src/main/java/com/sprint/findex_team6/error/ErrorCode.java
  src/main/java/com/sprint/findex_team6/error/ErrorResponse.java
  src/main/java/com/sprint/findex_team6/mapper/DashboardMapper.java
  src/main/java/com/sprint/findex_team6/mapper/IndexValMapper.java
  src/main/java/com/sprint/findex_team6/repository/IndexRepository.java
  src/main/java/com/sprint/findex_team6/repository/IndexValRepository.java
  src/main/java/com/sprint/findex_team6/service/IndexValService.java
  src/test/java/com/sprint/findex_team6/mapper/DashboardMapperTest.java
Labels: ✨ Feature, 🔨 Refactor

#32 feat: 자동 연동 설정 목록 조회
  build.gradle
  src/main/java/com/sprint/findex_team6/controller/AutoIntegrationController.java
  src/main/java/com/sprint/findex_team6/controller/SyncJobsController.java
  src/main/java/com/sprint/findex_team6/dto/AutoSyncConfigDto.java
  src/main/java/com/sprint/findex_team6/dto/request/AutoSyncConfigCursorPageRequest.java
  src/main/java/com/sprint/findex_team6/dto/request/AutoSyncConfigUpdateRequest.java
  src/main/java/com/sprint/findex_team6/dto/request/SyncCursorPageRequest.java
  src/main/java/com/sprint/findex_team6/dto/response/CursorPageResponseSyncDto.java
  src/main/java/com/sprint/findex_team6/entity/AutoIntegration.java
  src/main/java/com/sprint/findex_team6/repository/AutoIntegrationQuerydslRepository.java
  src/main/java/com/sprint/findex_team6/repository/AutoIntegrationRepository.java
  src/main/java/com/sprint/findex_team6/repository/AutoIntegrationRepositoryImpl.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkQuerydslRepository.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepository.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepositoryImpl.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepositoryQuerydsl.java
  src/main/java/com/sprint/findex_team6/service/AutoSyncConfigService.java
  src/main/java/com/sprint/findex_team6/service/SyncJobsSearchService.java
Labels: ✨ Feature

#34 feat: 배치에 의한 지수 데이터 연동 자동화
  src/main/java/com/sprint/findex_team6/FindexTeam6Application.java
  src/main/java/com/sprint/findex_team6/batch/BatchAutoSyncIndexData.java
  src/main/java/com/sprint/findex_team6/repository/AutoIntegrationRepository.java
  src/main/java/com/sprint/findex_team6/repository/IndexValRepository.java
  src/main/java/com/sprint/findex_team6/service/SyncInfoJobsService.java
Labels: ✨ Feature, 🐞 BugFix

#42 feat: add exception fix this and that
  src/main/java/com/sprint/findex_team6/config/QueryDSLConfig.java
  src/main/java/com/sprint/findex_team6/controller/IndexValController.java
  src/main/java/com/sprint/findex_team6/controller/SyncJobsController.java
  src/main/java/com/sprint/findex_team6/dto/DashboardDto.java
  src/main/java/com/sprint/findex_team6/dto/request/CursorPageRequest.java
  src/main/java/com/sprint/findex_team6/dto/response/CursorPageResponseSyncJobDto.java
  src/main/java/com/sprint/findex_team6/entity/Dashboard.java
  src/main/java/com/sprint/findex_team6/entity/IndexDataLink.java
  src/main/java/com/sprint/findex_team6/entity/IndexVal.java
  src/main/java/com/sprint/findex_team6/exception/SyncDataJobsServiceExceptionHandler.java
  src/main/java/com/sprint/findex_team6/exception/SyncJobErrorCode.java
  src/main/java/com/sprint/findex_team6/exception/syncjobs/DuplicateIndexException.java
  src/main/java/com/sprint/findex_team6/exception/syncjobs/FailedCallOpenApiException.java
  src/main/java/com/sprint/findex_team6/exception/syncjobs/NotFoundIndeValException.java
  src/main/java/com/sprint/findex_team6/exception/syncjobs/NotFoundIndexException.java
  src/main/java/com/sprint/findex_team6/exception/syncjobs/NotFoundItemException.java
  src/main/java/com/sprint/findex_team6/exception/syncjobs/SyncDataJobsServiceExceptionHandler.java
  src/main/java/com/sprint/findex_team6/exception/syncjobs/SyncFailedException.java
  src/main/java/com/sprint/findex_team6/exception/syncjobs/SyncJobErrorCode.java
  src/main/java/com/sprint/findex_team6/mapper/IndexValMapper.java
  src/main/java/com/sprint/findex_team6/repository/AutoIntegrationRepository.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkQuerydslRepository.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepository.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepositoryImpl.java
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepositoryQuerydsl.java
  src/main/java/com/sprint/findex_team6/repository/IndexRepository.java
  src/main/java/com/sprint/findex_team6/repository/IndexValRepository.java
  src/main/java/com/sprint/findex_team6/service/AutoSyncConfigService.java
  src/main/java/com/sprint/findex_team6/service/SyncDataJobsService.java
  src/main/java/com/sprint/findex_team6/service/SyncInfoJobsService.java
  src/main/java/com/sprint/findex_team6/service/SyncJobsSearchService.java
  src/main/resources/static/favicon.ico
  src/main/resources/static/index.html
Labels: ✨ Feature, 🐞 BugFix

#44 feat: 랭킹조회 기능 서비스 로직 변경
  src/main/java/com/sprint/findex_team6/dto/dashboard/ErrorResponse.java
  src/main/java/com/sprint/findex_team6/error/ErrorResponse.java
  src/main/java/com/sprint/findex_team6/repository/IndexValRepository.java
Labels: ✨ Feature

#58 fix: rank 오작동 수정
  .gitignore
  src/main/java/com/sprint/findex_team6/controller/IndexValController.java
  src/main/java/com/sprint/findex_team6/dto/dashboard/RankedIndexPerformanceDto.java
  src/main/java/com/sprint/findex_team6/exception/syncjobs/SyncDataJobsServiceExceptionHandler.java
  src/main/java/com/sprint/findex_team6/repository/IndexValRepository.java
  src/main/java/com/sprint/findex_team6/service/IndexValService.java
Labels: 🐞 BugFix

#60 fix: 업데이트 쿼리가 안나가던 현상 수정
  src/main/java/com/sprint/findex_team6/dto/request/AutoSyncConfigUpdateRequest.java
  src/main/java/com/sprint/findex_team6/service/AutoSyncConfigService.java
Labels: 🐞 BugFix

#61 feat: 지수 데이터 연동 시 중복 데이터 처리 추가
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepository.java
  src/main/java/com/sprint/findex_team6/repository/IndexValRepository.java
  src/main/java/com/sprint/findex_team6/service/SyncDataJobsService.java
Labels: ✨ Feature

#68 fix: 지수관리 목록 및 연동 관리 성공 실패 건수 수정
  src/main/java/com/sprint/findex_team6/repository/IndexDataLinkRepositoryImpl.java
  src/main/java/com/sprint/findex_team6/repository/IndexRepository.java
  src/main/java/com/sprint/findex_team6/service/IndexService.java
  src/main/java/com/sprint/findex_team6/service/SyncJobsSearchService.java
Labels: 🐞 BugFix
